services:
  web:
    build: .
    container_name: nanobanana_web
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs

  nginx:
    image: nginx:stable-alpine
    container_name: nanobanana_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Расположение фронта
      - /home/compas/VSCodeProjects/nanobanana/nanobanana/dist:/frontend/dist:ro
      # nginx конфиг
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # media
      - ./media:/app/media
    depends_on:
      - web
